name: Terraform CI/CD

on:
  push:
    paths:
      - "infra/**" # Monitor changes in the infra folder

jobs:
  infra-changes:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      TF_ROOT: infra # Set the Terraform working directory

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS Creds are set"

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      # Initialize Terraform
      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init

      #Validate Terraform
      - name: Terraform Validate
        working-directory: ${{ env.TF_ROOT }}
        run: terraform validate

      # Run Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ env.TF_ROOT }}
        run: terraform plan -out=tfplan

      #Run Terraform Apply
      - name: Terraform Apply
        working-directory: ${{ env.TF_ROOT }}
        run: terraform apply tfplan
